version: "3.7"
    
services:
  django-gunicorn-be:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: gunicorn --bind :8000 app.wsgi
